apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
spec:
  selector:
    matchLabels:
      app: python-api
  replicas: 1
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: mahlomojats/python-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_DATABASE
          value: "people_db"
