apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.api.name }}
  ports:
  - port: {{ .Values.api.servicePort }}
    targetPort: {{ .Values.api.port }}
