apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
